export const UserDataModel = {
  status: String,
  message: String,
  data: {
    distributor_id: (Number, -1),
    user_id: Number,
    name: String,
    email: String,
    phone: String,
    address: {
      postalcode_id: Number,
      postalcode: String,
      post_name: String,
      is_service_available: Boolean,
      city_id: Number,
      city_name: String,
      district_id: Number,
      district_name: String,
      state_id: Number,
      state_name: String,
      country_id: Number,
      country_name: String,
    },
    distributor_rank: {
      rank_id: Number,
      rank_title: String,
    },
    sponsor_distributor_id: Number,
    is_pcm_member: Boolean,
    is_pcm_order_eligible: Boolean,
    is_votm_member: Boolean,
    is_votm_order_eligible: Boolean,
  },
  error_type: String,
};